# Generated by Django 3.0.2 on 2020-01-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100)),
                ('release_year', models.CharField(max_length=8)),
                ('speciality', models.CharField(max_length=100)),
                ('employment', models.CharField(max_length=100)),
                ('army', models.CharField(max_length=100)),
                ('freelance', models.CharField(max_length=100)),
            ],
        ),
    ]
