# Generated by Django 3.0.2 on 2020-01-25 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100)),
                ('release_year', models.CharField(max_length=10)),
                ('employment', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('practice_one', models.CharField(max_length=100)),
                ('practice_two', models.CharField(max_length=100)),
                ('budget', models.CharField(choices=[('Бюджет', 'Бюджет'), ('Платник', 'Платник')], default='Бюджет', max_length=100)),
                ('vac', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='List_of_employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('worker', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students_base.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Skills_Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_base.Vacancy')),
            ],
        ),
        migrations.CreateModel(
            name='Skills_Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('fio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_base.Job')),
            ],
        ),
    ]
