# Generated by Django 3.0.2 on 2020-01-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='vacancy',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='worker',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
