# Generated by Django 3.0.2 on 2020-01-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='release_year',
            field=models.CharField(max_length=10),
        ),
    ]
