# Generated by Django 3.0.2 on 2020-01-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='vac',
            new_name='vacancy',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='worker',
            field=models.IntegerField(default=0),
        ),
    ]
