# Generated by Django 3.0.2 on 2020-01-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_base', '0002_auto_20200114_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='army',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='freelance',
            new_name='practice_one',
        ),
        migrations.AddField(
            model_name='job',
            name='practice_two',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='release_year',
            field=models.DateField(verbose_name='date of birth'),
        ),
    ]
