# Generated by Django 3.0.2 on 2020-01-26 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students_base', '0002_auto_20200125_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='vacancy',
            new_name='vacancy_st',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='worker',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students_base.Job'),
        ),
    ]
