# Generated by Django 3.0.2 on 2020-01-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_base', '0003_auto_20200123_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='worker',
            field=models.IntegerField(default=0),
        ),
    ]
