# Generated by Django 3.0.2 on 2020-01-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_base', '0003_auto_20200114_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='release_year',
            field=models.CharField(max_length=10),
        ),
    ]
