# Generated by Django 3.0.2 on 2020-01-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_base', '0004_auto_20200114_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='speciality',
        ),
        migrations.AlterField(
            model_name='job',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
