# Generated by Django 3.0.2 on 2020-01-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_base', '0005_auto_20200115_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='budget',
            field=models.CharField(choices=[('b', 'бюджет'), ('nb', 'внебюджет')], default='', max_length=9),
            preserve_default=False,
        ),
    ]
