# Generated by Django 3.0.2 on 2020-01-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_base', '0006_job_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='budget',
            field=models.CharField(choices=[('Бюджет', 'Бюджет'), ('Внебюджет', 'Внебюджет')], max_length=9),
        ),
    ]
