# Generated by Django 3.0.2 on 2020-01-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_base', '0008_auto_20200115_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='budget',
            field=models.CharField(choices=[('Бюджет', 'Бюджет'), ('Внебюджет', 'Внебюджет')], default='Бюджет', max_length=100),
        ),
    ]
