# Generated by Django 3.0.2 on 2020-02-02 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students_base', '0008_auto_20200127_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('call_time', models.DateTimeField()),
                ('comment', models.CharField(help_text='max 150 symbols', max_length=150)),
                ('fio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_base.Job')),
            ],
        ),
    ]
