# Generated by Django 3.0.2 on 2020-01-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_base', '0009_auto_20200115_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='code',
            field=models.CharField(choices=[('Бюджет', 'Бюджет'), ('Внебюджет', 'Внебюджет')], default='Другое', max_length=100),
        ),
    ]
