# Generated by Django 3.0.2 on 2020-02-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_base', '0009_calls'),
    ]

    operations = [
        migrations.AddField(
            model_name='calls',
            name='status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
