# Generated by Django 3.0.2 on 2020-01-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_base', '0010_auto_20200115_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='code',
            field=models.CharField(choices=[('Другое', 'Другое'), ('12.13.14 Программирование', '12.13.14 Программирование'), ('13.14.15 Защита информации', '13.14.15 Защита информации'), ('14.15.16 Разработчики', '14.15.16 Разработчики')], default='Другое', max_length=100),
        ),
    ]
