# Generated by Django 3.0.2 on 2020-02-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_base', '0011_job_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='email',
            field=models.EmailField(default='', help_text='foo@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='phone_number',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
