# Generated by Django 3.0.2 on 2020-01-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_base', '0011_auto_20200115_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
