# Generated by Django 3.0.2 on 2020-01-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_base', '0012_auto_20200115_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='budget',
            field=models.CharField(choices=[('Бюджет', 'Бюджет'), ('Платник', 'Платник')], default='Бюджет', max_length=100),
        ),
    ]
