# Generated by Django 3.0.2 on 2020-01-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_base', '0013_auto_20200115_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='List_of_employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment', models.CharField(max_length=100)),
            ],
        ),
    ]
