# Generated by Django 3.0.2 on 2020-02-08 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students_base', '0015_remove_specialty_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='college',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='students_base.College'),
            preserve_default=False,
        ),
    ]
