# Generated by Django 3.0.2 on 2020-02-14 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_base', '0016_specialty_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='notifications',
        ),
    ]
