# Generated by Django 3.0.2 on 2020-02-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_base', '0017_remove_job_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='vacancy_st',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
