# Generated by Django 3.0.2 on 2020-02-20 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students_base', '0020_auto_20200220_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='specialty',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='students_base.Group'),
            preserve_default=False,
        ),
    ]
