# Generated by Django 3.0.2 on 2020-02-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_base', '0021_auto_20200220_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
