# Generated by Django 3.0.2 on 2020-02-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_base', '0022_job_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
