# Generated by Django 3.0.2 on 2020-03-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_base', '0024_auto_20200225_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentimg',
            name='type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
